name: portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.2
  go_router: ^13.0.0
  firebase_core: ^2.24.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/logos/social/

  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: fonts/IBMPlexMono-Regular.ttf

    - family: Cabin
      fonts:
        - asset: fonts/Cabin_VariableFont.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
