{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 resolution;\n\nvec4 fragColor;\n\nvec3 flutterBlue;\nvec3 flutterNavy;\nvec3 flutterSky;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    flutterBlue = vec3(0.01960784383118152618408203125, 0.3254902064800262451171875, 0.69411766529083251953125);\n    flutterNavy = vec3(0.01568627543747425079345703125, 0.16862745583057403564453125, 0.3490196168422698974609375);\n    flutterSky = vec3(0.007843137718737125396728515625, 0.4901960790157318115234375, 0.99215686321258544921875);\n    vec2 st = FLT_flutter_local_FlutterFragCoord() / resolution;\n    vec3 color = vec3(0.0);\n    vec3 percent = vec3((st.x + st.y) / 2.0);\n    color = mix(mix(flutterSky, flutterBlue, percent * 2.0), mix(flutterBlue, flutterNavy, (percent * 2.0) - vec3(1.0)), step(vec3(0.5), percent));\n    fragColor = vec4(color, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "resolution",
      "rows": 2,
      "type": 10
    }
  ]
}